const QrFieldData = [
    {   id: "1",
        text: "link",
        isAuthenticated: false,
        inputFieldValues: [
                { id: "a1", label: "Link", type: "link", required: "required" },
                { id: "b1", label: "Logo", type: "link"},
            ],
    },
    {   id: "2",
        text: "email",
        isAuthenticated: false,
        inputFieldValues: [
                { id: "a2", label: "Email", type: "link", required: "required" }, 
                { id: "b2", label: "Subject", type: "link", required: "required" },
                { id: "c2", label: "Message", type: "textarea", required: "required" },
                { id: "d2", label: "Logo", type: "link"},
            ],
    },
    {   id: "3",
        text: "text",
        isAuthenticated: false,
        inputFieldValues: [
                { id: "a3", label: "Text", type: "link", required: "required"}, 
                { id: "b3", label: "Logo", type: "link" },
            ],
    },
    {   id: "4",
        text: "phone",
        isAuthenticated: false,
        inputFieldValues: [
                { id: "a4", label: "Phone", type: "link", required: "required" }, 
                { id: "b4", label: "Logo", type: "link" },
            ],
    },
    {   id: "5",
        text: "whatsapp",
        isAuthenticated: false,
        inputFieldValues:[
                { id: "a5", label: "whatsApp", type: "link", required: "required" }, 
                { id: "b5", label: "Logo", type: "link" },
            ],
    },
    {   id: "6",
        text: "wifi",
        isAuthenticated: false,
        inputFieldValues: [
                { id: "a6", label: "Network Name", type: "link", required: "required" }, 
                { id: "b6", label: "Network Type", type: "link", required: "required" },
                { id: "c6", label: "Password", type: "link", required: "required" }, 
                { id: "d6", label: "Logo", type: "link" },
            ],
    },
    {   id: "7",
        text: "app",
        isAuthenticated: true,
        inputFieldValues: [
                { id: "a7", label: "Play store or App Store", type: "link", required: "required" }, 
            ]
    },
    {   id: "8",
        text: "socials",
        isAuthenticated: true,
        inputFieldValues: [
                {id: "a8", label: "Socials", type: "text", required: "required" }, 
            ],
    },
];

export default QrFieldData;