const QRFieldData = [
    {   id:1,
        text: "link",
        logo: "",
    },
    {   id:2,
        text: "email",
        logo: "",
    },
    {   id:3,
        text: "text",
        logo: "",
    },
    {   id:4,
        text: "phone",
        logo: "",
    },
    {   id:5,
        text: "whatsapp",
        logo: "",
    },
    {   id:6,
        text: "wifi",
        logo: "",
    },
    {   id:7,
        text: "app",
        logo: "",
    },
    {   id:8,
        text: "socials",
        logo: "",
    },
];

export default QRFieldData;